---
- name: Enable ntpd
  service:
    name: ntpd
    enabled: yes
  notify: restart ntpd
- name: Synchronise clock
  command:
    argv: ['ntpdate', 'au.pool.ntp.org']
- name: Synchronise ntpd on startup
  copy:
    content: |
      ntpd_sync_on_start="YES"
    dest: /etc/rc.conf.d/ntpd
  notify: restart ntpd
- name: Config ntpd
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntpd
