---
- name: Install Airplay package
  pkgng:
    name: shairport-sync
    state: present
- name: Start D-Bus service
  service:
    name: dbus
    enabled: yes
    state: started
- name: Start mDNS service
  service:
    name: avahi-daemon
    enabled: yes
    state: started
- name: Configure Airplay service
  lineinfile:
    regexp: '^//\s+name = "%H";'
    line: '      name = "{{ services[inventory_hostname]["airplay"]["name"] }}";'
    path: /usr/local/etc/shairport-sync.conf
  notify: restart shairport-sync
- name: Enable Airplay service
  service:
    name: shairport-sync
    enabled: yes
  notify: restart shairport-sync
- name: Set mixer level
  copy:
    content: 'vol 100:100'
    dest: /var/db/mixer0-state
  notify: start mixer