---
# These tasks don't trigger any runtime changes, right now a reboot is
# necessary to apply the configuration
- name: Set hostname
  hostname:
    name: '{{ inventory_hostname }}.{{ site_domain }}'
    use: freebsd
- name: Configure interfaces
  copy:
    content: |
      ifconfig_{{ network_interface }}_ipv6="inet6 accept_rtadv"
      ifconfig_{{ network_interface }}_aliases="{{ network_aliases[inventory_hostname] }}"
    dest: /etc/rc.conf.d/netif
- name: Enable rtsold
  service:
    name: rtsold
    enabled: yes
- name: Configure routing
  copy:
    content: |
      defaultrouter="{{ default_router }}"
    dest: /etc/rc.conf.d/routing
- name: Configure name resolution
  copy:
    content: |
      name_servers="::1 127.0.0.1"
    dest: /etc/resolvconf.conf
- name: Remove default DHCP
  lineinfile:
    path: /etc/rc.conf
    regexp: '^ifconfig_DEFAULT'
    state: absent
- name: Enable IPv6 temporary addresses
  sysctl:
    name: net.inet6.ip6.use_tempaddr
    value: '1'
    sysctl_set: yes
    state: present
- name: Prefer use of IPv6 temporary addresses
  sysctl:
    name: net.inet6.ip6.prefer_tempaddr
    value: '1'
    sysctl_set: yes
    state: present
