---
- name: Install syslog-ng
  pkgng:
    name: syslog-ng
    state: present
- name: Enable syslog-ng
  service:
    name: syslog-ng
    enabled: yes
  notify: restart syslog-ng
- name: Configure syslog-ng
  template:
    src: syslog-ng.conf.j2
    dest: /usr/local/etc/syslog-ng.conf
  notify: restart syslog-ng
- name: Disable base syslogd
  service:
    name: syslogd
    state: stopped
    enabled: no
- meta: flush_handlers