---
- name: restart dhclient
  service: 
    name: dhclient
    state: restarted
    arguments: "{{ network_interface }}"
- name: restart sshd
  service:
    name: sshd
    state: reloaded
- name: rebuild aliases
  command:
    argv: ['newaliases']
- name: restart sendmail
  service:
    name: sendmail
    state: restarted