---
- name: Set hostname
  hostname:
    name: '{{ inventory_hostname }}.disasterarea.ninja'
    use: freebsd
- name: Update dhclient configuration
  template:
    src: dhclient.conf.j2
    dest: /etc/dhclient.conf
  notify: restart dhclient
# Subsequent tasks require network configuration, force dhclient handler
- meta: flush_handlers
- name: Set root password
  user:
    name: root
    password: '{{ root_password_hash }}'
- name: Disable SSH password login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#ChallengeResponseAuthentication'
    line: ChallengeResponseAuthentication no
  notify: restart sshd
- name: Install root CA certificates
  pkgng:
    name: ca_root_nss
    state: latest
- name: Forward root email
  lineinfile:
    path: /etc/aliases
    regexp: '^#\s+root:\s+me@my.domain'
    line: 'root:	{{ admin_email }}'
  notify: rebuild aliases
- name: Config sendmail
  block:
  - name: Remove sendmail config
    lineinfile:
      path: /etc/rc.conf
      regexp: '^sendmail_.*'
      state: absent
    notify: restart sendmail
  - name: Override default sendmail config
    copy:
      content: |
        sendmail_enable="NO"
        sendmail_submit_enable="YES"
        sendmail_outbound_enable="NO"
        sendmail_msp_queue_enable="NO"
      dest: /etc/rc.conf.d/sendmail
    notify: restart sendmail
- name: Send periodic email to admin
  copy:
    content: |
      daily_output="{{ admin_email }}"
      daily_status_security_output="{{ admin_email }}"
      weekly_output="{{ admin_email }}"
      weekly_status_security_output="{{ admin_email }}"
      monthly_output="{{ admin_email }}"
      monthly_status_security_output="{{ admin_email }}"
    dest: /etc/periodic.conf
- name: Send cron email to admin
  copy:
    content: |
      cron_flags="-m {{ admin_email }}"
    dest: /etc/rc.conf.d/cron
  notify: restart cron
- name: Set user password
  user:
    name: freebsd
    password: '*'