---
- name: Set hostname
  hostname:
    name: '{{ inventory_hostname }}'
    use: freebsd
- name: Update dhclient configuration
  template:
    src: dhclient.conf.j2
    dest: /etc/dhclient.conf
  notify: restart dhclient
# Subsequent tasks require network configuration, force dhclient handler
- meta: flush_handlers
- name: Disable SSH password login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#ChallengeResponseAuthentication'
    line: ChallengeResponseAuthentication no
  notify: restart sshd
- name: Install root CA certificates
  pkgng:
    name: ca_root_nss
    state: latest
- name: Config NTP
  copy:
    content: |
      ntpd_sync_on_start="YES"
    dest: /etc/rc.conf.d/ntpd
- name: Enable NTP
  service:
    name: ntpd
    enabled: yes
    state: started